# Задание 2
**Выполнил:** Руденко Андрей  
**Группа:** МГ-513

In [1]:
import numpy as np

1. Создайте нулевой вектор длины 10, пятое значение которго равно 1.

In [2]:
vector = np.zeros(10)
vector[4] = 1

print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


2. Создайте вектор, значения которого лежат в пределах от 10 до 49 (включительно).

In [3]:
vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


3. Отобразите все элементы вектора в обратном порядке (последний становится первым и т.д.).

In [5]:
reversed_vector = vector[::-1]

print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


4. Найдите индексы ненулевых элементов вектора [1,2,0,0,4,0].

In [6]:
arr = np.array([1, 2, 0, 0, 4, 0])

indexes = np.nonzero(arr)

print(indexes)

(array([0, 1, 4]),)


5. Создайте массив 3x3x3 со случайными элементами.

In [7]:
arr = np.random.random((3, 3, 3))

print(arr)

[[[0.4665241  0.31304756 0.48317428]
  [0.71578838 0.05892027 0.15616359]
  [0.29511171 0.36708764 0.91305513]]

 [[0.51387134 0.85263178 0.18614954]
  [0.94693464 0.02580494 0.00145973]
  [0.36765902 0.79545192 0.09263067]]

 [[0.24440301 0.93675194 0.5778496 ]
  [0.04744343 0.74451603 0.89039179]
  [0.82329225 0.29779127 0.52362949]]]


6. Создайте массив 10x10, состоящий из случайных значений и найдите минимум и максимум, а также среднее значение по каждой из осей.

In [9]:
arr = np.random.random((10, 10))

print(arr)

print("Минимум:", arr.min())
print("Максимум:", arr.max())

print("Среднее по столбцам:")
print(arr.mean(axis=0))

print("Среднее по строкам:")
print(arr.mean(axis=1))

[[0.00981644 0.43309412 0.51797081 0.63824039 0.19141105 0.07017866
  0.51189672 0.95406308 0.28838841 0.38722019]
 [0.9892635  0.10458343 0.23233619 0.3459315  0.33035731 0.51238443
  0.42464648 0.15556559 0.69201548 0.76307424]
 [0.71234094 0.89196681 0.09073319 0.29596308 0.22925101 0.61570462
  0.72689216 0.52486986 0.65080428 0.47612948]
 [0.18714527 0.54283639 0.33082125 0.78756968 0.31872266 0.08286293
  0.13744804 0.6791263  0.36566031 0.09532282]
 [0.5304838  0.8198952  0.61741198 0.6231649  0.97506684 0.35891654
  0.8394334  0.62174568 0.64276041 0.08656044]
 [0.41755171 0.95280351 0.42366215 0.21062204 0.14473873 0.04423188
  0.75011428 0.95144675 0.80332063 0.13404744]
 [0.64519197 0.92623129 0.92222744 0.51001926 0.56241408 0.91879654
  0.1833024  0.93171912 0.74359433 0.45696555]
 [0.04338802 0.60851379 0.96474911 0.22694732 0.10981726 0.78025982
  0.9002485  0.91989933 0.85777074 0.63420067]
 [0.31776783 0.16244955 0.50619127 0.32057255 0.47633123 0.70263517
  0.02000004

7. Создайте двумерный массив произвольного размера с единицами по периметру и нулями внутри.

In [10]:
arr = np.ones((6, 6))

arr[1:-1, 1:-1] = 0

print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


8. Добавьте границу (состоящую из нулей) в существующий массив.

In [11]:
arr = np.ones((5, 5))

new_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print(new_arr)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


9. Создайте матрицу 5x5 со значениями 1,2,3,4 лежащими ниже главной диагонали.

In [12]:
arr = np.diag([1, 2, 3, 4], k=-1)

print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


10. Создайте матрицу 8x8 и заполните ее нулями и единицами в шахматном порядке.

In [13]:
arr = np.zeros((8, 8), dtype=int)

arr[1::2, ::2] = 1
arr[::2, 1::2] = 1

print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


11. Как найти одинаковые значения в двух массивах? Проилюстрируйте примером.

In [14]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])

common = np.intersect1d(a, b)

print("Общие элементы:", common)

Общие элементы: [3 4 5]


12. Создайте матрицу, представляющую собой календарь на сентябрь 2020.

In [15]:
import calendar

cal = calendar.monthcalendar(2020, 9)

print(np.array(cal))

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30  0  0  0  0]]


13. Создайте матрицу 5x5, значения в строках которой варьируются от 0 до 4.

In [16]:
arr = np.tile(np.arange(5), (5, 1))

print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


14. Создайте матрицу 10x2, состоящую из случайных значений, представляющих декартовы координаты, переведите данные значения в полярные координаты.

In [17]:
arr = np.random.random((10, 2))

x = arr[:, 0]
y = arr[:, 1]

r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

print("Декартовы координаты:")
print(arr)

print("\nПолярные координаты:")
print("r =", r)
print("theta =", theta)

Декартовы координаты:
[[0.7581535  0.7684496 ]
 [0.45742757 0.9612676 ]
 [0.47837938 0.19748013]
 [0.62432767 0.12997717]
 [0.5540177  0.52054075]
 [0.67704746 0.8497491 ]
 [0.13666327 0.20198418]
 [0.57507323 0.93945254]
 [0.53666056 0.54744395]
 [0.18426516 0.07285913]]

Полярные координаты:
r = [1.07949595 1.06455407 0.51753767 0.63771397 0.76019621 1.08649289
 0.24387386 1.10149004 0.76661557 0.19814667]
theta = [0.79214251 1.12664758 0.39150108 0.20525555 0.75425409 0.89803313
 0.97594566 1.02150066 0.79534466 0.37653781]


15. Создайте вектор размером 10, состоящий из случайных значений и замените его максимальное значение нулем.

In [18]:
arr = np.random.randint(1, 100, 10)

print("Исходный массив:")
print(arr)

arr[arr.argmax()] = 0

print("После замены:")
print(arr)

Исходный массив:
[96  9 91 35 58  6 55 35 40 36]
После замены:
[ 0  9 91 35 58  6 55 35 40 36]


16. Создайте два массива $X$ и $Y$, постройте на их основе матрицу Коши ($C_{ij}=1 / \left(x_i - y_j\right)$, где $1 \le i \le m$, $1 \le j \le n$).

In [19]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7])

C = 1 / (x[:, np.newaxis] - y)

print(C)

[[-0.25       -0.2        -0.16666667]
 [-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


17. Рассмотрите два множества точек $P_0$ и $P_1$, описывающие отрезки в двумерном пространстве и множество точек $P$, как расчитать расстояние от каждой точки $j$ ($P[j]$) до каждой линии $i$ ($P_0[i]$, $P_1[i]$).

In [26]:
import numpy as np

# Начальные точки линий
P0 = np.array([[0, 0], [1, 1]])

# Конечные точки линий
P1 = np.array([[1, 0], [2, 2]])

# Точки
P = np.array([[1, 2], [3, 4]])

# Векторы линий
line_vec = P1 - P0

# Расстояния
distances = []

for point in P:
    point_distances = []

    for start, vec in zip(P0, line_vec):
        x0, y0 = point
        x1, y1 = start
        dx, dy = vec

        numerator = abs(dx * (y1 - y0) - (x1 - x0) * dy)
        denominator = np.sqrt(dx**2 + dy**2)

        distance = numerator / denominator

        point_distances.append(distance)

    distances.append(point_distances)

distances = np.array(distances)

print("Расстояния от точек до линий:")
print(distances)

Расстояния от точек до линий:
[[2.         0.70710678]
 [4.         0.70710678]]


18. Как найти самое частое значение в массиве чисел? Проиллюстрируйте примером.

In [27]:
arr = np.array([1, 2, 2, 3, 3, 3, 4, 5])

most_common = np.bincount(arr).argmax()

print("Самое частое значение:", most_common)

Самое частое значение: 3


19. Как получить $n$ наибольших значений в массиве? Проиллюстрируйте примером.

In [28]:
arr = np.array([5, 1, 9, 3, 14, 7, 20])

n = 3

largest = np.sort(arr)[-n:]

print(f"{n} наибольших значения:")
print(largest)

3 наибольших значения:
[ 9 14 20]


20. По результатам собеседования вам предлагают определенную зарплату. И конверт, который может случайным образом снизить или увеличить эту зарплату вдвое. Т.е., если сначала зарплата была $X$, то после вскрытия она может стать или $2X$ или $0.5X$. Как в среднем изменится зарплата, если соискатель решил открыть конверт?

In [29]:
import random

# Начальная зарплата
X = float(input("Введите начальную зарплату: "))

# Возможные варианты
salary_up = 2 * X
salary_down = 0.5 * X

# Математическое ожидание
expected_salary = (salary_up + salary_down) / 2

print("\nЕсли открыть конверт:")
print(f"Зарплата может стать: {salary_up}")
print(f"Или: {salary_down}")

print(f"\nСреднее ожидаемое значение: {expected_salary}")

# Процент изменения
percent_change = ((expected_salary - X) / X) * 100

print(f"Среднее изменение зарплаты: {percent_change:.2f}%")

Введите начальную зарплату:  100



Если открыть конверт:
Зарплата может стать: 200.0
Или: 50.0

Среднее ожидаемое значение: 125.0
Среднее изменение зарплаты: 25.00%
